name: Build site

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4.1.1
        with:
          ref: master

      - name: Install NodeJS
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build files
        run: npm run build

      - name: Copy dist to server with scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist"
          target: "/var/www/aahotel.amiraiman.dev/"
