name: Build site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout
        with:
          ref: master

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build files
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - name: Copy dist to server with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist"
          target: "/var/www/aahotel.amiraiman.dev/dist"
